### ISSUE TITLE
一部の画像や動画のリソースが502になる

### ISSUE THREAD

**Issue by KateSawada** [jack-app/jackweb3#129]
## 概要

![image](https://github.com/user-attachments/assets/ecf78769-87d2-46a8-b635-6ad9b0d58986)

↑のようになる

これらの記事で発生を確認
- https://www.jackapp.jp/blog/5c31c753-d4fb-4ecb-95b4-6cd9fae6aaa5
- https://www.jackapp.jp/blog/c9506fac-d77a-4cd8-8b71-d5de679e83e7

**Comment by Riku-0801** [comment]
@KateSawada 
自分の環境だと↓の記事は画像表示のバグが無いんですけど、スクリーンショットとかでバグっている箇所を送ってもらえますか？
https://www.jackapp.jp/blog/c9506fac-d77a-4cd8-8b71-d5de679e83e7

**Comment by KateSawada** [comment]
@Riku-0801 
今見たら，画像は全部表示されるようになってました

ただ，依然動画はダメな様子（こちらも502ではなくなっている）

![image](https://github.com/user-attachments/assets/7016d82e-6d1f-4450-bfb0-ee7da699e342)
![image](https://github.com/user-attachments/assets/d30fb45e-36ca-4611-aa57-08451f4a02e8)

**Comment by Riku-0801** [comment]
そもそも動画は未対応なので一旦Closeします。
